apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-sipx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-sipx
    app.kubernetes.io/part-of: tkwch-fix-0075-0045-app
  name: devfile-sample-sipx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-sipx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-sipx
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0045-tenant/tkwch-fix-0075-0045-app/devfile-sample-sipx@sha256:27a73f80ff22c6215624ff5caab9d582d38da27f6161178c97710a5437af3859
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
